### ISSUE TITLE
Upgrade to Gatsby 5

### ISSUE THREAD

**Issue by vitaliy-at-gatsby** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#14]
Hello there, 

Vitaliy (Senior Engineering Manager) from Gatsby here. Thank you for creating this great starter! Since your starter is listed on our official library (https://www.gatsbyjs.com/starters/), it is important to keep it on the latest major release of Gatsby. Doing so ensures your starter will continue to be listed in the library. 

If you haven’t seen the news already, we have released a beta version of Gatsby 5 and are on track to release the GA version in November. It would be great if you can upgrade this starter from v4 to v5 by then. Here are the docs on how to migrate: https://v5.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/

Let us know if you have any questions. Thanks again!

**Comment by konstantinruge** [comment]
Hey! Thanks for pointing that out. I will take a look at upgrade the starter 👍

**Comment by konstantinruge** [comment]
@vitaliy-at-gatsby Done -> https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal-theme/commit/d395c01984f39ce3a22402b87c1bd77731b43e2a 😊
