### ISSUE TITLE
How to edit the blog section?

### ISSUE THREAD

**Issue by lut3k-IT** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#15]
Hi @konstantinmuenster . How can I edit the blog section? For example i want to change heading. I see in `gathsby-theme-portfolio-minimal > src > templates > ArticleListing` that title, heading, label are hardcoded. And I don't know how this component is even loaded. /privacy and /imprint pages seem to work like a router, but /blog page looks like it's loading entirely.

I'd appreciate your help.

**Comment by konstantinruge** [comment]
Sorry for my late response. Meanwhile, I added an option to change the heading on the ArticleListing page:

https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/tree/main/gatsby-theme-portfolio-minimal#configuring-gatsby-configjs

Hope it helps!
