### ISSUE TITLE
Hero section disappearing

### ISSUE THREAD

**Issue by justinnais** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#2]
Hero section disappears when mouse over certain links. 
This only occurs when the URL provided in the `settings.json` is for a new page.

```json
"header": [
        { "label": "About", "url": "/#about" },
        { "label": "Blog", "url": "/blog" },
        { "label": "Features", "url": "/#features" },
        { "label": "Github", "url": "/#github" }
      ],
```

The blog link above causes the header to disappear. This is the same result for the links in the footer.

Mousing over the links will set the opacity to 0 for the section.
![hero-issue](https://user-images.githubusercontent.com/60305417/123798978-14293c80-d92b-11eb-8390-2c30d31d2054.gif)

**Comment by konstantinruge** [comment]
Good finding, thanks! I can reproduce it in development mode, it works fine however in production. Is it the same for you?

I just saw that there is an open issue for the described behavior in the Gatsby project (the rerender causes the animation to reset): https://github.com/gatsbyjs/gatsby/issues/29011

**Comment by justinnais** [comment]
That looks like the issue, and no issues with the production build - thanks for that!

**Comment by konstantinruge** [comment]
Alright! If it works fine in production, I think it is acceptable. Hopefully, it solves automatically with updates of Gatsby in the future. So I close this issue here for now 👍

**Comment by div-cowboy** [comment]
I'm still having a similar issue. I have a mega menu with images, and whenever you hover over the images, the state of the parent component is reset and the mega menu closes. Any recs on how to avoid this?

**Comment by konstantinruge** [comment]
I think I will refactor the implementation of animating/revealing sections. This should fix the disappearing. For now, I reopen this issue here and keep you posted

**Comment by mkoptewicz** [comment]
Hi! My hero section disappears when clicking on the menu link (doesn't matter which one). Sadly it occurs even when the site is live. Could you help me with this?

**Comment by konstantinruge** [comment]
@mkoptewicz Which version of the theme do you use? I released a quick fix that should solve the issue ([see here](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/commit/9e9e8d668b95872e8547a8062da35b186fcbfa92)). You need to have v2.6.1.

Edit: Just saw that this starter still uses v2.5.0 - I will update also the starter so that it uses the most recent version 👍

**Comment by konstantinruge** [comment]
@mkoptewicz @iamkratos I just released a new version of the theme that includes the refactoring of animations. You can update to [v2.6.2](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/releases/tag/v2.6.2)

I hope this will fix your issues with the disappearing sections. Let me know if it works or not 🤞

**Comment by mkoptewicz** [comment]
Hi! I'm currently using version 2.6.3. Everything seems fine and you can see the selected links as well! Cheers!

**Comment by konstantinruge** [comment]
That’s awesome! Thanks for responding @mkoptewicz 🙏
