### ISSUE TITLE
How can I opt out of privacy/imprint pages?

### ISSUE THREAD

**Issue by aschimmichanga** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#20]
Deleting them in `settings.json` AKA setting siteConfiguration's footer to [] causes a GraphQL error:
<img width="829" alt="image" src="https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal-theme/assets/44778757/60dcfbfd-c448-43b8-a4ed-9bb534fc8286">

**Comment by konstantinruge** [comment]
Hey @aschimmichanga! Have you checked whether it works when you run `gatsby clean` before starting the dev server again? If so, then it is definitely an issue - thanks for opening up!

**Comment by konstantinruge** [comment]
This has been fixed in v4.6.2 🙌
