### ISSUE TITLE
Comment section for blog 

### ISSUE THREAD

**Issue by bhuwan1998** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#22]
name: Comment Section for the blog 
about: Asking a way to implement comments on the blog with anonymous visitors 
title: 'Feature request'
labels: feature-request

I was wondering is there a way to extend the current blog implementation to add a comment section or does that require a CMS and another implementation of blog section on the website from scratch.

**Comment by konstantinruge** [comment]
Hey @bhuwan1998!

Great idea! Given the numerous ways of adding comments I don't see this feature added natively to the theme soon. But you could extend the theme yourself if you want to integrate comments in your site specifically. 

An easy way, for example, would be to use a provider like https://commentbox.io/ and shadow the `ArticleTemplate` component (see [Gatsby docs on shadowing](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/)).

**Comment by bhuwan1998** [comment]
Thanks @konstantinmuenster. I will try to implement it in my own project. Would you recommend using a CMS or using only something like commentbox.io?

**Comment by konstantinruge** [comment]
> Thanks @konstantinmuenster. I will try to implement it in my own project. Would you recommend using a CMS or using only something like commentbox.io?

Using a provider like commentbox.io is definitely easier, although it comes with limitations in terms of design etc. So depends on if you prefer simplicity or customization :)
