### ISSUE TITLE
Changing the size of the images in blog post

### ISSUE THREAD

**Issue by bhuwan1998** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#24]
Hi, I am trying to change the size of an image for one of my blog posts however the changes are not reflected in the blog post. Also is there a way to shadow the article section to make custom changes to how each blog post looks like. I know that all of them will follow a certain pattern. But I would like to change the width of the blog post if possible to fit in more graphs. Any help or guidance would be appreciated. 

This is how I am trying to change the height and width of the image in the blog post
```<img src="../../images/Articles/sentiment_analysis/code.png" alt ="Code" width="100" height="50" />```

![image](https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal-theme/assets/24411210/d08aad03-2e1d-4c5a-a65b-d76af11accde)

I tried many different combinations but the image remains the same.

**Comment by konstantinruge** [comment]
Hey @bhuwan1998! Regarding "a way to shadow the article section", do you mean the actual blog post page? Or the section on the frontpage that previews some of the blog posts?

If it concerns the former, you can find the relevant styles in this file: https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/gatsby-theme-portfolio-minimal/src/templates/Article/style.module.css

You could shadow this by following [this tutorial](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/) and define your own overrides for the page width and the image size.

Let me know if this already helps achieving what you had in mind 👍

**Comment by bhuwan1998** [comment]
Sorry I may have been unclear in stating that I was referring to the blog post page itself not the preview. I will shadow the page accordingly. Thank you for guiding me in the right direction.

**Comment by bhuwan1998** [comment]
Upon shadowing a css file I was able to see the changes of the blog post but when deploying nothing changes. It all remains the same as before. I don't understand why. 
<img width="298" alt="image" src="https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal-theme/assets/24411210/8f1ca7ce-8233-4310-826f-3d8c1d9d954f">

**Comment by konstantinruge** [comment]
Have you tried opening the site in an incognito window? Maybe it is some sort of caching.

**Comment by bhuwan1998** [comment]
Yeah I tried opening the site on multiple different devices on incognito and everything. Apparently this is something in relation to Gatsby and netlify deployments and not anything to do with this theme itself. Still looking for a solution atm.
