### ISSUE TITLE
Change the look for a blog post and add views at the bottom of the blog page 

### ISSUE THREAD

**Issue by bhuwan1998** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#25]
Hi @konstantinmuenster, I had a couple of doubts. You have mentioned before regarding shadowing to customise certain pages. However, is it possible to do the same for the blog post. If so is it possible to use google analytics to grab the views for a particular page and be dynamically updated on each blog post. And also be shown in the blog cards which are previous when we first go to the blog.

**Comment by konstantinruge** [comment]
Hey @bhuwan1998 and sorry for the late reply!

Hm, good question. I think it might be possible to customize the blog post page by shadowing the following file: https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/gatsby-theme-portfolio-minimal/src/templates/Article/index.tsx

We use this as a template when generating blog post pages dynamically upon build.

Hope it helps!

**Comment by bhuwan1998** [comment]
Hi @konstantinmuenster, just a small follow up question regarding the blog. Is it possible to get page total count of page views from google analytics. As a junior developer I just wanted some advice.

**Comment by konstantinruge** [comment]
> Hi @konstantinmuenster, just a small follow up question regarding the blog. Is it possible to get page total count of page views from google analytics. As a junior developer I just wanted some advice.

Usually, these get tracked automatically in Google Analytics since each post has a distinct page and hence page view. So there's no need to do anything special on the theme-side.

**Comment by bhuwan1998** [comment]
Sorry @konstantinmuenster I meant I want to display the page count at the bottom to show total views on a blog post.

**Comment by konstantinruge** [comment]
ah, I see. For that, you'd need to edit the template file that I referenced earlier. Either you store the page count value in a database or you are able to retrieve the count from the Google API directly (not sure about the latter).

**Comment by bhuwan1998** [comment]
I think there's a library I researched that is basically an API used to get data from Google analytics. But anyway I need to change the footer by shadowing the blog page. So I guess you've put me on the correct path. Thanks 👍

**Comment by bhuwan1998** [comment]
Having a little trouble shadowing the Article.tsx because of styles.module.css import. Every other import not from the module itself has been shadowed in the directory. So I found out that it may be because of the tsconfig.json. So initially I had just shadowed the styles.module.css to change the look of the articles in terms of colours. Do you have any advice how to fix this ? 


<img width="506" alt="image" src="https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal-theme/assets/24411210/d9c97a6a-6b4c-4f32-89ed-940c0efcc9c7">

<img width="556" alt="image" src="https://github.com/konstantinmuenster/gatsby-starter-portfolio-minimal-theme/assets/24411210/07e000b5-5252-42f7-82c8-1387eb311fa4">
