### ISSUE TITLE
Resume button file location

### ISSUE THREAD

**Issue by JakubHojsan** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#3]
Hello!

Using the default directory, ```/resume.pdf```, when built with ```gatsby build``` the site displays a cached version of the resume. I am not sure why this is, but changing out the resume.pdf inside of the main directory does not seem to change anything. 

Am I supposed to instead put the resume in the public/static directory?

Thank you!

**Comment by konstantinruge** [comment]
Hey! Thanks for pushing the project and contributing good questions! 

The easiest solution is to place the `resume.pdf` file in the `static` directory and then reference it like `/resume.pdf` in the settings.json. You can see an exemplary implementation here: https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/tree/main/example-site 

Also, I just recognized that the pdf file is missing in this starter project. I will add it 👍
