### ISSUE TITLE
No visual indicator when selecting links with keyboard

### ISSUE THREAD

**Issue by mkoptewicz** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#4]
Hey. I have the accessibility issue as mentioned in the title. Could you please add some visual clue regarding which link is currently selected?

**Comment by konstantinruge** [comment]
That's a good point, thanks! I will add it as soon as I can 👍

**Comment by konstantinruge** [comment]
@mkoptewicz I've added an outline for buttons and links in [v2.6.3](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/releases/tag/v2.6.3) 😉
