### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by TeenageMutantCoder** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#5]
As this repository does not yet have a license, no one is allowed to use or edit this repository without explicit consent from the owner. The previous repository of this template had an MIT license, but this one has no such thing. 

From GitHub's [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/)
> Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

**Comment by konstantinruge** [comment]
Thanks, I indeed forgot this! License is added 🙏
