### ISSUE TITLE
Addition of other social profiles

### ISSUE THREAD

**Issue by alopezari** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#6]
Hi!

First of all thank for sharing this awesome portfolio starter with us, it looks amazing :)

I started playing with it and wanted to add other social profiles, like Twitter, for instance. I added it to the configuration file inside the content path (just where the other social profiles are) but Gatsby raised an error when loading the page, saying something like "unknown social profile".

Probably I'm missing something. Is there an easy way to change/add other social profiles?

Thanks!

**Comment by konstantinruge** [comment]
Hi @alopezari! Glad to hear that, thanks a lot 👋 

Regarding your issue: No, actually you don't miss anything. I just didn't come to add more social profiles yet 😄  So, only a few are available and can be added. Which platforms do you need in specific? I will add them to the theme, then you just need to update your `gatsby-theme-portfolio-minimal` package and you can use them.

If you want to add your own custom profiles instead, you would have to do the following:
1. Extend the [SocialProfiles](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/gatsby-theme-portfolio-minimal/src/components/SocialProfiles/index.tsx) component and its [configuration](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/gatsby-theme-portfolio-minimal/src/components/SocialProfiles/configuration.ts) with your custom platforms. You can do this by [theme shadowing](https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/shadowing/).
2. Add the platform's icon in the [icons directory](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/tree/main/gatsby-theme-portfolio-minimal/src/components/Icon) and extend the [Icon](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/gatsby-theme-portfolio-minimal/src/components/Icon/index.tsx) component accordingly. This can be done via shadowing as well.

Whatsoever, you can also just give me the missing social profile platforms and I will add them. Then, they will be available to everyone ☺️

**Comment by alopezari** [comment]
Hi @konstantinmuenster , thanks for your response!

The only social profile I miss there is Twitter, I think it will be useful for other people as well since it's one of the most used social networks for developers. It would be great if you could add it to the theme.

However, we're here to learn, so I will try to add it on my own too. Thanks for the explanation!

**Comment by konstantinruge** [comment]
@alopezari Alright, it has been more to it than what I mentioned. You can check [here](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/commit/81f4e60979b3e6a1b873ed33f9297ae2189afb05) what I changed. I also just released an updated version of the theme. So you can update to `v2.6.4` and should be able to add a Twitter profile. 

Hopefully, this works for you ☺️

**Comment by alopezari** [comment]
Wow, thank you very much for the super fast update! Looking forward to updating the version and checking your changes.

Cheers!
