### ISSUE TITLE
"Github" capitalization on buttons should be corrected to "GitHub" in npm module

### ISSUE THREAD

**Issue by geewey** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#7]
Hi Konstatin, I am a big fan of this portfolio design and am interested in updating to the newest design with the enhanced Gatsby features.

I noticed that there is a small typo in the SocialProfile enum - where "Github" should be properly capitalized as "GitHub":
![Screen Shot 2021-12-15 at 11 47 38 PM](https://user-images.githubusercontent.com/6667268/146310195-ed75abcd-4fbb-43e7-aeb1-48b05effcd12.png)

Since it's in the NPM modules, I don't believe I make this correction locally. Can you please help? Thank you!

**Comment by konstantinruge** [comment]
Hey @geewey ! Thanks for the hint - I changed not only the enum but also the display label configuration (as this represents the actual value in the frontend). I just released an updated [v3.0.1](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/releases/tag/v3.0.1) ☺️
