### ISSUE TITLE
Make projects images clickable

### ISSUE THREAD

**Issue by gpozzi** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#8]
I've been watching user behavior for my portfolio page and I find people don't always see GitHub icons as clickable and sometimes exit the page without having clicked any link, defeating (for them) the purpose of the whole portfolio, which is to showcase project details.

I also see some of them try to click the big image expecting some interaction. I think making those images clickable (and to be able to customize the link) would improve overall user experience and "catch" some of the ones that can't find what we want to showcase.

**Comment by konstantinruge** [comment]
Thanks for sharing the insights! I will add it to the theme and let you know once I published a new version 😊

**Comment by konstantinruge** [comment]
@gpozzi I just released a new version 3.1.0 that has clickable project images 🙌
