### ISSUE TITLE
Making Your Website Shareable on LinkedIn

### ISSUE THREAD

**Issue by towardsuffering** [konstantinmuenster/gatsby-starter-portfolio-minimal-theme#9]
The website doesn't seem to comply with Open Graph Protocol and was wondering if you know how to implement these changes here https://www.linkedin.com/help/linkedin/answer/a521928/making-your-website-shareable-on-linkedin?lang=en so that I can show off the website on my LinkedIn with an image thumbnail. As of now, I cannot add an image thubmnail because the site is not OGP compliant I believe.

**Comment by konstantinruge** [comment]
@towardsuffering Hey, thanks for suggesting 🙌   I just published a new version (v3.2.0) that has a `thumbnail` property inside settings.json (see [example-site](https://github.com/konstantinmuenster/gatsby-theme-portfolio-minimal/blob/main/example-site/content/settings.json#L5))

Hope this works for you!
